version: '2.1'
volumes:
  esdata:
    driver: local
services:
  game:
    ports:
      - 9292:9292
    build:
      context: game
      dockerfile: Dockerfile.game
      args:
        git_sha1: ${GIT_SHA1}
    volumes:
      - ./log:/tmp/log
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9292']
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.1
    links:
      - elasticsearch
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5601']
  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.1
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/var/log
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ipc: shareable
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']
