filebeat:
  prospectors:
    -
      paths:
        - "/var/log/bandit.log"

processors:
- add_cloud_metadata:

output:
  elasticsearch:
    hosts: ['elasticsearch:9200']
    username: elastic
    password: changeme
    index: bandit
