filebeat:
  prospectors:
    -
      paths:
        - "/var/log/bandit.log"

processors:
  - add_cloud_metadata:
  - decode_json_fields:
      fields: ['name', 'hostname', 'pid', 'msg', 'fruits']

output:
  elasticsearch:
    hosts: ['elasticsearch:9200']
    username: elastic
    password: changeme
    index: bandit
