filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/*.log

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
